---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance_os
    image: ${DOCKER_IMAGE:-eniocarboni/docker-ubuntu-systemd:latest}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /sbin/init
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
