---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dockerdistro:
          - eniocarboni/docker-ubuntu-systemd:22.04
          - eniocarboni/docker-ubuntu-systemd:20.04
          - eniocarboni/docker-ubuntu-systemd:18.04
          - eniocarboni/docker-rockylinux-systemd:latest
          - eniocarboni/docker-rockylinux-systemd:8
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install ansible, molecule and dependences
        run: pip3 install ansible molecule[docker] docker yamllint ansible-lint
       # See: https://github.com/geerlingguy/ansible-role-mysql/issues/422
      - name: Disable AppArmor on Ubuntu/Debian.
        run: |
            set -x
            sudo apt-get update
            sudo apt-get install -y apparmor-profiles
            echo "# disable mysql profile" | sudo tee -a /etc/apparmor.d/usr.sbin.mysqld
            echo "# disable mariadb profile" | sudo tee -a /etc/apparmor.d/usr.sbin.mariadb
            sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
        if: ${{ contains(matrix.dockerdistro, 'ubuntu') }}
      - name: Run Molecule tests
        run: molecule test
        env:
          DOCKER_IMAGE: ${{ matrix.dockerdistro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
